// The visitor id doubles as the "sync code": whoever holds it can read and write that board's data.
const VISITOR_KEY = "visionboard_visitor_id";
const ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; // no look-alikes (0/O, 1/I)

export const FALLBACK_ID = "anonymous-browser";

function generateCode() {
  const bytes = new Uint8Array(16);
  if (typeof crypto !== "undefined" && crypto.getRandomValues) crypto.getRandomValues(bytes);
  else bytes.forEach((_, i) => (bytes[i] = Math.floor(Math.random() * 256)));
  const chars = Array.from(bytes, (b) => ALPHABET[b % ALPHABET.length]);
  return "VB-" + [0, 4, 8, 12].map((i) => chars.slice(i, i + 4).join("")).join("-");
}

// Accepts new "VB-XXXX-XXXX-XXXX-XXXX" codes and the UUIDs generated by earlier versions.
export function normalizeCode(input: string): string | null {
  const v = input.trim();
  if (/^VB-([A-Za-z2-9]{4}-){3}[A-Za-z2-9]{4}$/i.test(v)) return v.toUpperCase();
  if (/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v)) return v.toLowerCase();
  return null;
}

export function getVisitorId(): string {
  if (typeof window === "undefined") return FALLBACK_ID;
  try {
    let id = localStorage.getItem(VISITOR_KEY);
    if (!id) {
      id = generateCode();
      localStorage.setItem(VISITOR_KEY, id);
    }
    return id;
  } catch {
    return FALLBACK_ID;
  }
}

export function setVisitorId(id: string) {
  localStorage.setItem(VISITOR_KEY, id);
}
