-- Weekly actions per life area (Monday-based weeks).
create table if not exists public.vision_board_actions (
  id bigint generated by default as identity primary key,
  visitor_id text not null,
  client_id text not null,
  area text not null,
  week_start date not null,
  text text not null check (char_length(text) between 1 and 200),
  done boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists vision_board_actions_visitor_client_unique
  on public.vision_board_actions (visitor_id, client_id);

create index if not exists vision_board_actions_visitor_week_idx
  on public.vision_board_actions (visitor_id, week_start);

alter table public.vision_board_actions enable row level security;

drop policy if exists "vision board actions are publicly readable" on public.vision_board_actions;
create policy "vision board actions are publicly readable"
  on public.vision_board_actions for select to anon, authenticated using (true);

drop policy if exists "vision board actions are publicly insertable" on public.vision_board_actions;
create policy "vision board actions are publicly insertable"
  on public.vision_board_actions for insert to anon, authenticated with check (true);

drop policy if exists "vision board actions are publicly updatable" on public.vision_board_actions;
create policy "vision board actions are publicly updatable"
  on public.vision_board_actions for update to anon, authenticated using (true) with check (true);

drop policy if exists "vision board actions are publicly deletable" on public.vision_board_actions;
create policy "vision board actions are publicly deletable"
  on public.vision_board_actions for delete to anon, authenticated using (true);
