create table if not exists public.vision_board_views (
  id bigint generated by default as identity primary key,
  visitor_id text not null,
  viewed_at timestamptz not null default now(),
  view_date date not null,
  created_at timestamptz not null default now()
);

create index if not exists vision_board_views_visitor_date_idx
  on public.vision_board_views (visitor_id, view_date);

create index if not exists vision_board_views_viewed_at_idx
  on public.vision_board_views (viewed_at);

create unique index if not exists vision_board_views_visitor_date_unique
  on public.vision_board_views (visitor_id, view_date);

alter table public.vision_board_views enable row level security;

drop policy if exists "vision board views are publicly readable" on public.vision_board_views;
create policy "vision board views are publicly readable"
  on public.vision_board_views
  for select
  to anon, authenticated
  using (true);

drop policy if exists "vision board views are publicly insertable" on public.vision_board_views;
create policy "vision board views are publicly insertable"
  on public.vision_board_views
  for insert
  to anon, authenticated
  with check (true);
